export const personalInfo = {
  name: "Adel Baselizadeh",
  location: "Oslo, Norway",
  email: "adelb@ifi.uio.no",
  github: "https://github.com/Adelbaseli",
  linkedin: "https://www.linkedin.com/in/adel-baselizadeh-779719b1/",
  profilePicture: "/profile_photo_updated.jpeg",
  heroDescription:
    "I enjoy building AI systems that learn from different types of data, whether it is visual, temporal, textual, audio, or multimodal. I am interested in developing AI models that understand complex information, reason over it, and act through agentic AI systems. My experience covers the full ML development pipeline, from data collection and preprocessing to model development, training, evaluation, and deployment. I have applied AI across diverse domains, from psychology and sports science to human motion analysis, healthcare, audio, and robotics. I'm passionate about exploring new AI methods and applying them to problems across different domains.",
};

export const workExperience = [
  {
    company: "RITMO Centre",
    location: "Oslo, Norway",
    position: "Applied ML Engineer & AI Researcher",
    period: "2024 - Present",
    achievements: [
      "Build deep learning models across vision, audio, and time-series data for psychology, sports science, and healthcare applications.",
      "Apply vision-language and large language models to improve robot perception and context-aware navigation in shared human environments.",
      "Design statistical analysis pipelines, including hypothesis testing and A/B testing, and provide AI/ML consulting across interdisciplinary projects.",
    ],
    tags: ["ML/AI", "LLM/VLM", "Computer Vision"],
  },
  {
    company: "University of Oslo (UiO)",
    location: "Oslo, Norway",
    position: "PhD Fellow, AI / Informatics",
    period: "2020 - 2024",
    achievements: [
      "Worked with multimodal sensing data (RGB, thermal, depth, LiDAR, wearable sensors) for human activity and behavior analysis.",
      "Designed sensor fusion pipelines combining feature-, data-, and decision-level fusion across heterogeneous sensing modalities.",
      "Developed reinforcement learning approaches for adaptive decision-making and robot control.",
      "Delivered end-to-end ML pipelines, from data collection through training to real-world evaluation and user studies.",
    ],
    tags: ["Multimodal DL", "ML/AI", "Computer Vision", "RL"],
  },
  {
    company: "Sharif Technology Services Complex",
    location: "Tehran, Iran",
    position: "Software Engineer",
    period: "2018 - 2020",
    achievements: [
      "Implemented software-, processor-, and hardware-in-the-loop (SIL/PIL/HIL) test environments for control systems.",
      "Applied sensor and data fusion techniques (EKF, UKF) for dynamic systems analysis.",
      "Developed RL algorithms to support control system design and validation.",
    ],
    tags: ["Sensor Fusion", "SIL", "PIL", "HIL"],
  },
  {
    company: "Djavad Mowafaghian Center for Intelligent NeuroRehabilitation Technologies",
    location: "Tehran, Iran",
    position: "R&D Engineer",
    period: "2016 - 2018",
    achievements: [
      "Designed real-time control software for robotic rehabilitation systems, including the SBARA balance-assessment and rehabilitation robot.",
      "Integrated sensors, actuators, and embedded hardware into real-time robotic prototypes.",
      "Implemented real-time controllers in MATLAB/Simulink and xPC Target for human-interactive robotic platforms.",
    ],
    tags: ["Robotics", "Control"],
  },
];

export const education = [
  {
    institution: "University of Oslo (UiO)",
    location: "Oslo, Norway",
    degree: "Ph.D. in Informatics, AI",
    period: "2020 - 2024",
    achievements: [],
  },
  {
    institution: "Sharif University of Technology",
    location: "Tehran, Iran",
    degree: "M.Sc. in Mechanical Engineering",
    period: "2014 - 2016",
    achievements: [],
  },
  {
    institution: "Amirkabir University of Technology",
    location: "Tehran, Iran",
    degree: "B.Sc. in Mechanical Engineering",
    period: "2010 - 2014",
    achievements: [],
  },
];

export const skills = {
  programmingLanguages: ["Python", "C++", "SQL", "MATLAB", "R"],
  aiAndMachineLearning: [
    "Machine Learning",
    "Deep Learning",
    "Multimodal DL (RNNs, CNNs, Transformers)",
    "Machine Vision",
    "Time-Series Analysis",
    "LLMs / VLMs",
  ],
  mlFrameworks: ["PyTorch", "TensorFlow", "Scikit-learn", "XGBoost"],
  dataAndStorage: [
    "NumPy",
    "Pandas",
    "Matplotlib",
    "Seaborn",
    "PostgreSQL",
    "Databricks",
  ],
  devOpsAndTools: [
    "Docker",
    "Singularity",
    "Apptainer",
    "Microsoft Azure",
    "AWS",
    "MLflow",
    "FastAPI",
    "CI/CD",
    "Git",
    "CLI",
  ],
};

// The technique/method a project is built around. Shown as filter tag
// chips above the project grid; a project can belong to more than one.
// Order controls the order the chips appear in (only techniques with
// >=1 matching project show).
export const techniqueCategories = [
  "Time Series Analysis",
  "Computer Vision",
  "Audio & Speech",
  "Reinforcement Learning",
  "AI Agents & LLMs",
];

// The application domain a project belongs to. Kept in the data model and
// shown in the project detail modal, but no longer rendered on the compact
// project cards (removed to free up space for bigger images).
export const domainTags = [
  "Human-Robot Interaction",
  "Human Activity Recognition",
  "Multimodal Sensing",
  "Sports Science",
  "Psychology",
  "Audio",
  "Robotics & Control",
];

export const projects = [
  {
    title: "PriMA-Care: Privacy-Preserving Multimodal Dataset for Care Robots",
    image: "/projects/prima-care-dataset.png",
    github: "https://dl.acm.org/doi/abs/10.1145/3610978.3640701",
    techniques: ["Computer Vision"],
    domains: ["Human-Robot Interaction", "Multimodal Sensing"],
    description: [
      "Designed and collected a multimodal sensor dataset capturing how people interact with a care robot, covering 27 real-world activities from 17 participants.",
      "Instrumented a TIAGo robot with 8+ sensor types, from cameras and lidar to wearables and force/torque sensors, to study privacy trade-offs between modalities.",
      "Released the dataset publicly to support future research on privacy-preserving activity recognition in human-robot interaction.",
    ],
    details: [
      "Recorded 17 participants performing 27 activities spanning physical human-robot interaction, user gestures, and general presence detection around a TIAGo care robot.",
      "Instrumented the robot with a wide range of sensors, RGB, depth, thermal, 2D/3D lidar, ultra-wideband, wearable IMU, force/torque sensors, and the robot's own arm-joint encoders, to capture the same activities from many privacy/utility trade-off points at once.",
      "Data collection was approved by the Norwegian Centre for Research Data (NSD), with all participants giving informed consent to public release.",
      "Built to let researchers directly compare how well different sensor modalities, including privacy-preserving ones like lidar and IMU, perform on the same activities relative to conventional RGB cameras.",
      "Used as the evaluation benchmark for several follow-up projects on this page, including the 3D lidar activity recognition and transfer learning projects.",
      "Publicly released as a shared resource for the human-robot interaction and activity recognition research community.",
    ],
  },
  {
    title: "Privacy-Preserving Activity Recognition for Human-Robot Interaction",
    image: "/projects/lidar-har-hri.png",
    github: "https://ieeexplore.ieee.org/abstract/document/11369549",
    techniques: ["Time Series Analysis"],
    domains: ["Human-Robot Interaction", "Multimodal Sensing"],
    description: [
      "A multimodal deep-learning system that lets a care robot recognize what a person is doing around it, from handing over an object to commanding it with gestures.",
      "Combines 3D Lidar with a wrist-worn wearable and the robot's force/torque sensors, so no cameras or personally identifiable data are needed.",
      "Reaches 80%+ recognition accuracy across 9 activities by fusing all three sensors, using CNN, LSTM, Seq2Seq, and PointNet++ models.",
    ],
    details: [
      "Designed separate deep-learning models per sensor: a ConvLSTM network for the wearable and force/torque time-series data, and a PointNet++ network for the 3D Lidar point clouds.",
      "Explored two ways to merge the sensors: combining raw data early (data-level fusion) versus combining each model's learned features (feature-level fusion) through a Seq2Seq mechanism for the Lidar stream.",
      "Trained and evaluated the models on 9 real human-robot interaction activities, e.g. giving an object, holding the robot's hand while walking, stopping it, commanding it to rotate, captured on a TIAGo robot.",
      "Feature-level fusion of all three sensors was the clear winner, reaching 80.73% accuracy, well above any single sensor or a two-sensor combination.",
      "Every sensor was chosen specifically for being privacy-preserving, so the system understands user activity without capturing faces, video, or other identifiable data, which matters for home and healthcare settings.",
      "Trained large point-cloud models efficiently despite heavy compute demands, by extracting only the relevant, moving regions of each Lidar scan.",
    ],
  },
  {
    title: "Transfer Learning for Privacy-Preserving Activity Recognition",
    image: "/projects/multimodal-transfer-learning.png",
    github: "https://ieeexplore.ieee.org/abstract/document/11217600/",
    techniques: ["Computer Vision"],
    domains: ["Human Activity Recognition", "Multimodal Sensing"],
    description: [
      "Compared large general-purpose multimodal models against activity-recognition-specific models for recognizing what a person is doing around a robot.",
      "Tested across RGB, IMU, and depth sensors, and combinations of them, to see how well each generalizes beyond its original training data.",
      "Found that fusing privacy-preserving sensors (depth + IMU) nearly matched RGB-based accuracy, losing only about 5%, while revealing far less about a person's identity.",
    ],
    details: [
      "Trained a lightweight classification head on top of frozen, pretrained backbones for each modality, evaluated with leave-one-subject-out cross-validation on the PriMA-Care dataset.",
      "Compared two families of backbones: models built specifically for activity recognition versus large general-purpose multimodal models (ImageBind, LanguageBind) never trained on activity data.",
      "The general-purpose models consistently outperformed the activity-recognition-specific ones, reaching up to 98.29% accuracy (RGB + IMU) versus 94.97% for the best specialized combination (RGB + depth).",
      "Tested how easily each model could identify individual people, rather than activities, as a proxy for privacy leakage: RGB-based models were the most identifying, IMU and depth far less so.",
      "Fusing privacy-preserving sensors (depth + IMU) reached 93.14% accuracy, only a small drop from RGB-based approaches, a good trade-off for meaningfully better privacy.",
      "Also tested zero-shot classification, recognizing activities with no fine-tuning at all, reaching up to 82.85% accuracy, a promising direction for adding new activities without collecting new labeled data.",
    ],
  },
  {
    title: "Wi-Fi-Based Sleep Posture Monitoring",
    image: "/projects/wifi-sleep-posture.png",
    github: "https://ieeexplore.ieee.org/abstract/document/11369717/",
    techniques: ["Time Series Analysis"],
    domains: ["Human Activity Recognition", "Multimodal Sensing"],
    description: [
      "Built a sleep posture monitoring system that uses ordinary Wi-Fi signals instead of cameras, so it works in the dark and needs no wearables.",
      "Captured Wi-Fi Channel State Information (CSI) from low-cost ESP32 devices placed around a bed, under three blanket thicknesses and from four receiver positions.",
      "A simple neural network classified supine vs. side-sleeping with up to 98% accuracy, even through a thick blanket.",
    ],
    details: [
      "Used low-cost ESP32 Wi-Fi microcontrollers to capture Channel State Information (CSI), how Wi-Fi signals bend and reflect around a body, as a completely passive, camera-free sensing modality.",
      "Collected data from 10 participants sleeping in three postures (supine, left-side, right-side) under three blanket conditions (none, thin, thick), with sensors placed at four body-level positions around the bed.",
      "Preprocessed the raw CSI signal, removing null subcarriers, filtering outliers, and applying a low-pass filter, before feeding it into a simple multilayer perceptron classifier.",
      "Evaluated with leave-one-subject-out cross-validation to make sure the model generalizes to people it wasn't trained on, not just memorized poses.",
      "The hip-level receiver gave the most reliable results, reaching 94-98% accuracy distinguishing supine from side-sleeping across all blanket conditions.",
      "Demonstrates that affordable, off-the-shelf Wi-Fi hardware can offer a private, non-intrusive alternative to cameras or wearables for sleep and health monitoring.",
    ],
  },
  {
    title: "Predicting User Movement for Safer Human-Robot Interaction",
    image: "/projects/pose-prediction-hri.png",
    github: "https://ieeexplore.ieee.org/abstract/document/10260298",
    techniques: ["Computer Vision"],
    domains: ["Human-Robot Interaction", "Multimodal Sensing"],
    description: [
      "Built a privacy-preserving system that tracks a person's upper-body pose using only a thermal camera and depth sensor, no RGB video.",
      "Trained a lightweight Seq2Seq deep learning model to predict where a person's body will be a moment in the future, compensating for sensing lag.",
      "Predicting the user's movement made a robot up to 17% faster to react and up to 25% more accurate at following a moving hand.",
    ],
    details: [
      "Combined a thermal camera and a depth sensor, calibrated together via homography and pinhole projection, to reconstruct a person's 3D upper-body joint positions without ever capturing an RGB image.",
      "Used Openpose on thermal images, rather than the usual RGB input, to locate body joints in 2D before lifting them to 3D with the depth sensor.",
      "Designed a modified Seq2Seq (encoder-decoder) model, adding residual connections, an attention mechanism, bidirectional RNNs, and Time2Vec time embeddings, to predict a person's future joint positions from their recent movement.",
      "Optimized the model to run locally on a robot's onboard processor rather than in the cloud, cutting its computational cost by 34% for the same prediction accuracy.",
      "Tested on a TIAGo robot in two real scenarios: following a moving hand, and reacting to a hand entering or leaving its safety zone.",
      "Predicting the user's future pose improved hand-following accuracy by up to 25% and cut the robot's collision-avoidance reaction time by up to 17%, without needing any privacy-invasive cameras.",
    ],
  },
  {
    title: "Can Machine Learning Distinguish Elite from Non-Elite Rowers?",
    image: "/projects/rowing-skill-classification.png",
    github: "https://reference-global.com/download/article/10.2478/ijcss-2025-0007.pdf",
    techniques: ["Time Series Analysis"],
    domains: ["Sports Science", "Human Activity Recognition"],
    description: [
      "Built machine learning models (MLPs, CNNs, GRUs) that classify rowers as elite or non-elite from ergometer motion-capture data.",
      "Extracted joint angles and stroke-phase features from full-body motion capture to describe rowing technique.",
      "The best models reached 94-100% accuracy, showing that subtle differences in upper- and lower-body coordination separate skilled from novice rowers.",
    ],
    details: [
      "Collected motion-capture data from rowers of different skill levels performing on a rowing ergometer, tracking joint positions throughout the stroke cycle.",
      "Computed rowing-specific joint angles across the stroke phases as input features describing technique in a compact, interpretable way.",
      "Compared multiple model families, MLPs, CNNs, GRUs, and a combined CNN-GRU architecture, to see which best captures the movement patterns that separate elite from non-elite rowers.",
      "The MLP model reached 100% accuracy using the full feature set, and 94% even with a reduced feature set, showing the task is well suited to machine learning despite a small dataset.",
      "Found that coordination between upper- and lower-body limbs was particularly informative for telling skill levels apart.",
      "Suggests these models could support coaches and analysts with objective, data-driven talent identification and technique feedback.",
    ],
  },
  {
    title: "Reinforcement-Learning-Tuned Model Predictive Control for Robot Manipulators",
    image: "/projects/mpc-rl-manipulator-obstacle-avoidance.png",
    github: "https://ieeexplore.ieee.org/abstract/document/9945504",
    techniques: ["Reinforcement Learning"],
    domains: ["Robotics & Control"],
    description: [
      "Combined Nonlinear Model Predictive Control (NMPC) with reinforcement learning so a 6-DOF robot arm can plan collision-free motion around obstacles.",
      "Used RL (Q-learning) to continuously tune the NMPC's cost function and constraints, instead of relying on a fixed, hand-tuned controller.",
      "Improved the control loop's efficiency by up to 21% while keeping the safety guarantees of a traditional model-based controller.",
    ],
    details: [
      "Built an NMPC structure that doubles as a function approximator for RL's value and action-value functions, so both frameworks share the same underlying parameters.",
      "Parameterized the cost function, system constraints, and the manipulator's dynamic model, then used a Q-learning/temporal-difference algorithm to adjust them online.",
      "Applied the framework to a simulated 6-DOF robot manipulator tasked with reaching a target pose while avoiding static obstacles in its workspace.",
      "Showed the learned parameter adjustments increase closed-loop control performance by up to 21% versus a fixed-parameter NMPC baseline.",
      "Kept the interpretability and stability benefits of MPC while adding the adaptability of a model-free learning approach.",
    ],
  },
  {
    title: "Privacy vs. Utility Trade-offs Across Vision-Based Sensors for Care Robots",
    image: "/projects/vision-sensor-privacy-utility-tradeoff.png",
    github: "https://ieeexplore.ieee.org/abstract/document/10731223",
    techniques: ["Computer Vision"],
    domains: ["Human-Robot Interaction", "Psychology"],
    description: [
      "Ran a technical and user-study comparison of RGB, thermal (color and mono-color), and depth sensors for monitoring people around care robots.",
      "Surveyed 18 younger adults and interviewed 10 elderly participants to measure how each sensor type is perceived in terms of privacy.",
      "Found mono-color thermal cameras gave the best balance, matching RGB's monitoring usefulness while being perceived as far more privacy-preserving.",
    ],
    details: [
      "Compared sensors across four technical tasks: pose tracking, presence detection, vital-sign monitoring, and facial/emotion recognition.",
      "Designed and ran a mixed-methods user study (survey plus semi-structured interviews) across two age groups to capture both quantitative ratings and qualitative reasoning about privacy.",
      "Applied Friedman, Conover, and Mann-Whitney U tests to check for significant differences in perceived privacy across sensor types and age groups.",
      "Found participant age had no significant effect on privacy perception, but sensor type did, with RGB rated as least private.",
      "Delivered concrete recommendations for choosing vision sensors in care-robot deployments based on both technical performance and user trust.",
    ],
  },
  {
    title: "Does Matching a Robot's Approach Speed to Yours Make It Feel Warmer?",
    image: "/projects/robot-approach-velocity-perception.png",
    github: "https://ieeexplore.ieee.org/abstract/document/10557976",
    techniques: ["Computer Vision"],
    domains: ["Human-Robot Interaction", "Psychology"],
    description: [
      "Studied whether an assistive robot that matches a person's walking speed while approaching them is perceived as warmer and more comfortable.",
      "Used 2D Lidar and video to track participants' walking velocity, gestures, and facial expressions during real human-robot approach scenarios.",
      "Found that speed-matching increased perceived warmth and reduced discomfort, and that adding a small social gesture (a handshake or greeting) boosted engagement further.",
    ],
    details: [
      "Combined Lidar-based motion tracking with video recordings to capture walking velocity, gestures, facial expressions, and engagement during each approach.",
      "Built a questionnaire based on the RoSAS (Robotic Social Attributes Scale) plus open-ended questions to measure comfort, competence, naturalness, and warmth.",
      "Ran a controlled human-robot approach scenario on a TIAGo robot, testing whether matching the robot's approach speed to the participant's own walking speed changed their perception of it.",
      "Combined thematic analysis of open-ended responses with statistical analysis of the questionnaire scores.",
      "Found that adding a simple social interaction (handshake or greeting) further improved participants' engagement with the robot.",
    ],
  },
  {
    title: "How Age Changes What Robot Approach Speed Feels Comfortable",
    image: "/projects/noisy-velocity-matching-age-diversity.png",
    github: "https://dl.acm.org/doi/abs/10.1145/3610978.3640546",
    techniques: ["Computer Vision"],
    domains: ["Human-Robot Interaction", "Psychology"],
    description: [
      "Ran a pilot study testing whether matching, randomly varying (\"noisy\"), or fixing a robot's approach speed changes how comfortable, interactive, and natural it feels.",
      "Compared 10 younger adults against 10 elderly participants using a TIAGo robot and RGB-camera-based (OpenPose) velocity tracking.",
      "Found the two age groups wanted opposite things: younger participants preferred speed-matching, while elderly participants preferred a slow, steady, predictable approach.",
    ],
    details: [
      "Designed three approach conditions: a fixed default speed, a speed matched to the participant's own walking pace, and a speed randomly varied by ±25% around it.",
      "Used an RGB camera and OpenPose-based pose tracking to estimate each participant's walking velocity from video, with no wearable sensors involved.",
      "Ran the young-participant sessions at a university robotics lab and the elderly-participant sessions on-site at a care facility.",
      "Collected comfort, interactivity, and naturalness ratings after each approach, keeping participants blind to which condition they experienced.",
      "Concluded that a one-size-fits-all approach speed doesn't work: assistive robots should adapt their behavior to the age and demographics of the person they're approaching.",
    ],
  },
  {
    title: "Real-Time Self-Tuning Neuro-Fuzzy Control for Robot Manipulators",
    image: "/projects/neuro-fuzzy-control-manipulator.png",
    github: "https://ieeexplore.ieee.org/abstract/document/9646224",
    techniques: ["Reinforcement Learning"],
    domains: ["Robotics & Control"],
    description: [
      "Built a model-free ANFIS (neuro-fuzzy) controller for robot manipulators that tunes itself in real time instead of needing offline training.",
      "Applied an emotional-learning-inspired update rule so an agent continuously evaluates and adjusts the controller's neural-network parameters during operation.",
      "Reached sub-1-degree tracking error on a 2-DOF manipulator, and stayed robust even with 50% parameter and 20% control-signal uncertainty.",
    ],
    details: [
      "Designed an ANFIS-type controller for the trajectory-tracking problem, removing its usual dependency on a pre-collected offline training dataset.",
      "Introduced a real-time learning agent that monitors control performance and updates the neural-network component's parameters on the fly.",
      "Validated the approach in both joint-space and operational-space (end-effector) formulations of a 2-DOF manipulator model.",
      "Achieved normalized RMS tracking error below 1 degree per joint in simulation.",
      "Stress-tested robustness by injecting 50% uncertainty into the manipulator's physical parameters and 20% into the control signal, with the controller remaining stable.",
    ],
  },
  {
    title: "Dual Process Dreamer: Combining Fast and Slow Thinking for Agent Decision-Making",
    image: "/projects/dual-process-dreamer.png",
    github: "https://www.scitepress.org/Papers/2026/142432/142432.pdf",
    techniques: ["Reinforcement Learning"],
    domains: ["Robotics & Control"],
    description: [
      "Designed an agent architecture inspired by dual-process theory (\"thinking, fast and slow\") that switches between a quick RL policy and a slower planning algorithm.",
      "Unified both decision-making systems with a shared learned world model, tested on the Sokoban puzzle game.",
      "Matched the accuracy of the slow, deliberate system while relying on the fast system most of the time, showing a real efficiency gain from adaptive switching.",
    ],
    details: [
      "Combined a fast reinforcement-learning policy network (System 1) with a slower Monte Carlo Tree Search planner (System 2), unified through a shared learned world model.",
      "Implemented and compared two different switching mechanisms for choosing between System 1 and System 2: a learned classifier and a simulation-based rule.",
      "Evaluated the architecture on Sokoban, a puzzle game that requires long-horizon planning to avoid irreversible mistakes.",
      "Showed the combined system reaches a success rate similar to always using the slow planner, while using the fast policy for most decisions.",
      "Demonstrated that a more tightly integrated dual-process architecture, sharing one world model, can outperform earlier, more loosely coupled proposals.",
    ],
  },
  {
    title: "Wrist-Worn Gesture Recognition for Camera-Free Robot Commands",
    image: "/projects/wrist-imu-gesture-recognition.png",
    github: "https://ieeexplore.ieee.org/abstract/document/11396715",
    techniques: ["Time Series Analysis"],
    domains: ["Human Activity Recognition"],
    description: [
      "Built a privacy-preserving gesture recognition system that lets people command a robot using simple hand and arm movements, with no cameras at all.",
      "Captured motion from a single wrist-worn IMU (accelerometer, gyroscope, magnetometer) and classified 7 gesture classes plus a neutral \"no command\" state.",
      "A hybrid CNN-LSTM model reached about 95% recognition accuracy across participants using leave-one-subject-out cross-validation.",
    ],
    details: [
      "Collected a dedicated dataset from 10 participants performing 7 distinct command gestures (move forward/back/left-right, horizontal/vertical spin, wave, up-down) plus a neutral state.",
      "Used a single MbientLab wrist IMU device rather than multiple sensors or cameras, prioritizing simplicity and privacy over sensor coverage.",
      "Designed a hybrid CNN-LSTM architecture to jointly capture the spatial and temporal structure of the IMU signal.",
      "Evaluated with leave-one-subject-out cross-validation to test generalization to unseen users, not just memorized motion patterns.",
      "Reached approximately 95% recognition accuracy across all gesture classes, enabling safe, camera-free gesture control for human-robot interaction.",
    ],
  },
  {
    title: "Online Deep RL for Real-Time NMPC Tuning in Collision-Free Robot Manipulation",
    image: "/projects/drl-nmpc-collision-free-manipulation.png",
    github: "https://ieeexplore.ieee.org/abstract/document/10927488",
    techniques: ["Reinforcement Learning"],
    domains: ["Robotics & Control"],
    description: [
      "Paired Nonlinear Model Predictive Control (NMPC) with online deep reinforcement learning to tune a 7-DOF robot arm's collision-avoidance behavior in real time.",
      "Benchmarked five DRL algorithms (PPO, APPO, SAC, DDPG, TD3) as parameter tuners against a fixed, expert-tuned NMPC baseline.",
      "Cut setpoint control error by 53%, sped up path planning by 30%, and improved collision-free planning success by 39% over the fixed-parameter baseline.",
    ],
    details: [
      "Treated NMPC and DRL as two separate, cooperating systems, with DRL acting as a high-level decision-maker that adjusts NMPC's parameters in real time.",
      "Modeled the TIAGo robot's 7-DOF redundant arm manipulator using its kinematic Jacobian to relate joint velocities to end-effector motion.",
      "Benchmarked five established continuous-action DRL algorithms, PPO, APPO, SAC, DDPG, and TD3, as NMPC parameter tuners.",
      "Compared each learned tuner against a conventional NMPC controller with parameters fixed by a human expert, across a range of simulated dynamic obstacle scenarios.",
      "Achieved a 39% improvement in successful collision-free path planning, a 53% reduction in setpoint control error, and 30% faster path planning versus the expert-tuned baseline.",
    ],
  },
  {
    title: "AI-Based Movement-Type Classification Using 2D Lidar Data",
    image: "/projects/lidar-movement-classification.png",
    github: "https://github.com/Adelbaseli",
    techniques: ["Time Series Analysis", "Computer Vision"],
    domains: ["Human Activity Recognition", "Human-Robot Interaction"],
    description: [
      "A student project built on the PriMA-Care dataset I collected, classifying five movement types (walking, running, abnormal gait, walker use, wheelchair use) from privacy-preserving 2D Lidar data.",
      "Evaluated CNN, CNN-LSTM, CNN-GRU, and VGG16 transfer-learning architectures on ankle-height Lidar scans.",
      "The best CNN model reached 91% accuracy on held-out test subjects, with lighter CNN+GRU/CNN+LSTM variants offering a strong accuracy/speed trade-off.",
    ],
    details: [
      "Uses the PriMA-Care dataset (collected on a TIAGo robot with an ankle-height 2D Lidar) to classify five movement types: normal walking, running, abnormal walking, walker use, and wheelchair use.",
      "Compared multiple deep learning architectures, CNNs, CNN-LSTM and CNN-GRU hybrids, and VGG16 transfer learning, to study the trade-off between raw-signal modeling and image-based feature extraction.",
      "Evaluated with subject-level 6-fold cross-validation on 12 participants plus 2 fully held-out test subjects, to test generalization to unseen users.",
      "The best CNN model, capturing spatio-temporal features directly from raw Lidar scans, reached 91% accuracy on the held-out subjects.",
      "Demonstrates a further real-world use of the PriMA-Care dataset for privacy-preserving human activity recognition in care robotics.",
    ],
  },
  {
    title: "Adaptive Tidying Robots: Learning from Interaction and Observation",
    image: "/projects/adaptive-tidying-robots.png",
    github: "https://ieeexplore.ieee.org/abstract/document/10871003",
    techniques: ["AI Agents & LLMs"],
    domains: ["Human-Robot Interaction"],
    description: [
      "Built a software framework that combines large language models and vision-language models so a service robot can learn a person's own tidying-up preferences instead of following one fixed rule set.",
      "Enabled open-vocabulary object and receptacle recognition via VLMs, so the robot can handle objects it has never seen before.",
      "Reached 87.4% accuracy selecting the correct receptacle for unseen objects on a text-based benchmark, and validated the full pipeline in simulation.",
    ],
    details: [
      "Combined an LLM for learning and reasoning about tidying-up rules with VLMs for open-vocabulary object/receptacle detection, replacing the fixed object-label training of prior tidying-up robots.",
      "Learns household-specific tidying preferences through interaction and observation (via HRI), rather than assuming one universal rule set applies to every home.",
      "Evaluated in two stages: a text-based benchmark isolating rule-learning accuracy, and a simulated environment testing full end-to-end tidying performance.",
      "Reached 87.4% accuracy picking the correct receptacle for previously unseen objects, including receptacle categories the system had never encountered.",
      "Contributed to the system design and evaluation as part of a multi-institution collaboration between the University of Oslo and Kyushu University.",
    ],
  },
  {
    title: "Multi-Speaker Speech Detection and Localization (Ongoing)",
    image: "/projects/in-progress.webp",
    github: "https://github.com/Adelbaseli",
    techniques: ["Audio & Speech"],
    domains: ["Audio"],
    description: [
      "Ongoing project developing a multi-head encoder-decoder deep learning architecture to detect, identify, and localize multiple simultaneous speakers in noisy acoustic environments.",
      "Investigating time-domain audio features and simulated room acoustics to study how well models trained on simulated audio transfer to real recordings.",
      "Aims to unify speech detection, speaker tracking, and speaker localization in one multi-task model rather than separate pipelines.",
    ],
    details: [
      "Targets the classic \"cocktail party problem\": detecting, identifying, tracking, and localizing multiple speakers at once in a noisy, dynamic acoustic scene.",
      "Designing a multi-task, multi-head encoder-decoder architecture so a single shared representation can support speech detection, speaker ID/tracking, and localization simultaneously.",
      "Exploring time-domain audio features as an alternative to standard frequency-domain features (MFCCs, STFT) for these tasks.",
      "Using simulated room acoustics (image-source, ray tracing, and wave-equation methods) to generate training data, and studying how well models generalize from simulation to reality.",
      "Motivated by human-robot interaction, where reliable speaker detection and localization is a key part of a robot's acoustic perception of its surroundings.",
    ],
  },
  {
    title: "Multimodal AI-Based Drumming Sound Generation (Ongoing)",
    image: "/projects/in-progress.webp",
    github: "https://www.mn.uio.no/ifi/studier/masteroppgaver/robin/air-drum.html",
    techniques: ["Audio & Speech"],
    domains: ["Audio", "Multimodal Sensing"],
    description: [
      "Ongoing project building an AI-based multimodal drumming simulator that generates realistic drum sounds from motion, muscle activity, and gaze data.",
      "Designing a data collection protocol at RITMO combining motion capture, EMG, gaze tracking, video, and synchronized audio/MIDI recordings of real drumming.",
      "Will compare early, feature-level, and late fusion strategies to see which combination of sensing modalities produces the most expressive, realistic generated sound.",
    ],
    details: [
      "Aims to map human drumming gestures (arm, wrist, and stick movement, striking location, speed, and intensity) to realistic synthesized drum sounds.",
      "Designing a multimodal dataset combining motion capture, EMG muscle-activity sensors, gaze tracking, video, and synchronized audio/MIDI recordings.",
      "Plans to train deep learning models (CNNs, RNNs/LSTMs, Transformers, or hybrids) that predict MIDI parameters from the combined sensor streams.",
      "Will compare data-level, feature-level, and decision-level fusion strategies to identify which modality combinations most improve generated-sound accuracy and expressivity.",
      "Being developed at the RITMO Centre for Interdisciplinary Studies in Rhythm, Time and Motion, University of Oslo.",
    ],
  },
  {
    title: "Audio-Visual Voice Activity Detection",
    image: "/projects/audio-visual-vad.webp",
    github: "https://github.com/Adelbaseli/audio-visual-vad",
    techniques: ["Audio & Speech"],
    domains: ["Audio"],
    description: [
      "Building a frame-level voice activity detection system; audio-only at this stage, with audio-visual fusion (lip motion) planned as a future extension.",
      "Developed and evaluated a log-mel CRNN model for voice activity detection on the GRID corpus.",
      "A real-time browser demo and ONNX export are planned next steps, not yet built.",
    ],
    details: [
      "Current stage: developed and evaluated a log-mel CRNN for offline voice activity detection on the GRID audio-visual speech corpus, training on one speaker and validating on a held-out speaker.",
      "Planned next: export the trained model to ONNX and build a real-time browser demo that runs voice activity detection directly on microphone input via onnxruntime-web.",
      "Planned after that: a lip-fusion extension adding MediaPipe Face Landmarker lip-motion tracking as a second input stream for added robustness in noisy, multi-speaker settings.",
    ],
  },
  {
    title: "LLM/VLM-Guided Fuzzy MPC Tuning for Human-Aware Robot Navigation (Ongoing)",
    image: "/projects/agentic-llm-vlm-mpc-navigation.png",
    github: "https://github.com/Adelbaseli",
    techniques: ["AI Agents & LLMs"],
    domains: ["Human-Robot Interaction"],
    description: [
      "Ongoing project combining a vision-language model (VLM) and large language model (LLM) with a fuzzy-logic layer to tune a Model Predictive Controller's parameters in real time for safer robot navigation around people.",
      "A YOLO-based object detector and VLM analyze the scene (split into a 9-region grid) to assess path status, collision risk, and pedestrian motion direction, feeding a trajectory-prediction module and an LLM that adjusts the MPC's cost-function weights and constraints on the fly.",
      "Also developing a separate agentic AI system built with LangChain to orchestrate this pipeline, still in progress.",
    ],
    details: [
      "Uses a YOLO object detector plus a vision-language model to interpret the robot's camera view, dividing it into a 9-region grid and outputting each detected object's type, region, distance, motion direction, path status, and a risk level.",
      "Feeds a trajectory-prediction module (a transformer-style encoder-decoder) that forecasts nearby pedestrians' future paths.",
      "An LLM, guided by a fuzzy-logic layer, interprets the combined risk/trajectory information and adjusts the MPC's setpoint and collision cost-function weights, generates new waypoints, and can trigger a verbal safety alert when risk is high.",
      "Targets human-aware navigation: keeping a mobile robot's path efficient in open corridors while dynamically becoming more cautious as people get close.",
      "In parallel, developing an agentic AI system using LangChain to orchestrate the perception-to-control pipeline; both the navigation framework and the agentic wrapper are still ongoing work.",
    ],
  },
  {
    title: "Using Robotic Mechanical Perturbations for Enhanced Balance Assessment",
    image: "/projects/sbara-balance-assessment.png",
    github: "https://iopscience.iop.org/article/10.1016/j.medengphy.2020.07.006/pdf",
    techniques: ["Reinforcement Learning"],
    domains: ["Robotics & Control"],
    description: [
      "Designed and built a robotic balance-assessment platform (SBARA) that applies controlled, repeatable mechanical perturbations to a standing user in two directions.",
      "Combined dual servo actuators, force sensors for center-of-pressure measurement, and real-time visual feedback to create a controllable dynamic posturography device.",
      "Showed in a 10-subject study that adding mechanical perturbations significantly increased the sensitivity of balance-performance indices, especially in the anterior-posterior direction.",
    ],
    details: [
      "Developed a two-actuator rotating platform (mediolateral and anterior-posterior) using servo motors, planetary gears, and a spatial four-bar transmission mechanism, plus a full kinematic model relating motor angles to platform rotation.",
      "Instrumented the platform with four single-axis strain-gauge force sensors to compute the user's center of pressure (CoP) in real time, with a monitor providing visual CoP feedback.",
      "Characterized the device's dynamics experimentally, achieving a 0.19 s time constant and 0.85 Hz bandwidth in both rotation axes.",
      "Ran a controlled experiment with 10 healthy subjects performing a balance task with and without mechanical perturbations, measuring 7 center-of-pressure indices.",
      "Found that mechanical perturbations significantly increased the sensitivity of nearly all balance indices to the subject's performance, most notably in the anterior-posterior direction.",
    ],
  },
];

export const awards = [
  {
    name: "Lorem Ipsum Award",
    issuer: "Lorem Organization",
    date: "Jan 2020",
    type: "International",
    position: "First Place",
  },
];